#pragma once

#include <FastLED.h>

// INFO
#define CX_BOARD_INFO_ID "cx"
#define CX_BOARD_INFO_NAME "ConnectorX"
#define CX_BOARD_INFO_VERSION "1.0.0"
#define CX_BOARD_INFO_USB_VENDOR_ID ""
#define CX_BOARD_INFO_USB_PRODUCT_ID ""
#define CX_BOARD_INFO_USB_DEBUG_PRODUCT_ID ""
#define CX_BOARD_INFO_REGULATOR_OUTPUT_MA 3000.0
#define CX_BOARD_INFO_SKU 00001
#define CX_BOARD_INFO_SERIAL_NUMBER 000000000001

// PINS
#define CX_BOARD_PINS_I2C_1_SDA 14
#define CX_BOARD_PINS_I2C_1_SCL 15
#define CX_BOARD_PINS_SPI_0_TX 19
#define CX_BOARD_PINS_SPI_0_RX 16
#define CX_BOARD_PINS_SPI_0_SCK 18
#define CX_BOARD_PINS_SPI_1_TX 11
#define CX_BOARD_PINS_SPI_1_RX 12
#define CX_BOARD_PINS_SPI_1_SCK 10
#define CX_BOARD_PINS_SPI_1_CS0 13
#define CX_BOARD_PIN_SD_CS 17
#define CX_BOARD_PINS_INDICATOR_LED_ALIVE 25
#define CX_BOARD_PINS_INDICATOR_STATUS_LED_R 23
#define CX_BOARD_PINS_INDICATOR_STATUS_LED_G 24
#define CX_BOARD_PINS_INDICATOR_STATUS_LED_B 28

// FEATURES
#define CX_BOARD_FEATURES_ENABLE_LED 1
#define CX_BOARD_FEATURES_ENABLE_MODULES 1
#define CX_BOARD_FEATURES_ENABLE_SCREEN 1
#define CX_BOARD_FEATURES_ENABLE_MIC 0
#define CX_BOARD_FEATURES_ENABLE_DIO 1
#define CX_BOARD_FEATURES_ENABLE_AIO 1
#define CX_BOARD_FEATURES_HAS_INDICATORS 1
#define CX_BOARD_FEATURES_HAS_SD_CARD 1
#define CX_BOARD_FEATURES_HAS_CAN_BUS 0

// LED
#define CX_BOARD_LED_POWER_DRAW_MA 60.0
#define CX_BOARD_LED_CHANNEL_COUNT 1
// CHANNEL 1
#define CX_BOARD_LED_CHANNEL_1_KEY "1"
#define CX_BOARD_LED_CHANNEL_1_ENUM_NAME CHAN0
#define CX_BOARD_LED_CHANNEL_1_PIN 2
#define CX_BOARD_LED_CHANNEL_1_ENABLED_PIN 6
#define CX_BOARD_LED_CHANNEL_1_SELECTOR_PIN 255
#define CX_BOARD_LED_CHANNEL_1_HIDDEN 0

// DEVICES
#define CX_BOARD_DEVICES_MAX_COUNT 3
#define CX_BOARD_DEVICES_ENABLE_I2C 1
#define CX_BOARD_DEVICES_ENABLE_SPI 1
#define CX_BOARD_DEVICES_ENABLE_UART 0

// SCREEN
#define CX_BOARD_SCREEN_I2C_ADDRESS 0x3C
#define CX_BOARD_SCREEN_WIDTH_PX 128
#define CX_BOARD_SCREEN_HEIGHT_PX 64

// DIO
#define CX_BOARD_DIO_DIO0_NAME "DIO0"
#define CX_BOARD_DIO_DIO0_PIN 20
#define CX_BOARD_DIO_DIO1_NAME "DIO1"
#define CX_BOARD_DIO_DIO1_PIN 21

// AIO
#define CX_BOARD_AIO_AIO0_NAME "AIO0"
#define CX_BOARD_AIO_AIO0_PIN 26
#define CX_BOARD_AIO_AIO1_NAME "AIO1"
#define CX_BOARD_AIO_AIO1_PIN 27

// MIC
